drop table if exists member CASCADE;
create table member(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

--sql 파일은 인텔리제이 ultimate에서 제공...    이런거 쓰면 좋은게 git같은거 쓸때 버전관리가 됨--
